# Generated by Django 4.0.2 on 2022-03-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booktitle', models.CharField(max_length=50, verbose_name='Title')),
                ('author', models.CharField(max_length=30, verbose_name='Author')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
            ],
        ),
    ]
