# Generated by Django 4.0.2 on 2022-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0002_alter_textbook_author_alter_textbook_booktitle_and_more'),
        ('users', '0002_delete_wishlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Title')),
                ('textbooks', models.ManyToManyField(to='catalogue.Textbook')),
            ],
        ),
    ]
