# Generated by Django 4.0.2 on 2022-03-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
