# Generated by Django 4.0.2 on 2022-03-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_alter_textbook_author_alter_textbook_booktitle_and_more'),
        ('users', '0005_alter_wishlist_textbooks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='textbooks',
            field=models.ManyToManyField(related_name='wishlists', to='catalogue.Textbook'),
        ),
    ]
