# Generated by Django 4.0.2 on 2022-03-30 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_fraud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fraud',
            name='report',
            field=models.CharField(max_length=100),
        ),
    ]
